// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzxo1yw9NgUaymQabk42r0EzTaMhMor0A',
    appId: '1:941029947680:web:6bb15e1283a511a00eff45',
    messagingSenderId: '941029947680',
    projectId: 'food-delivery-116d0',
    authDomain: 'food-delivery-116d0.firebaseapp.com',
    storageBucket: 'food-delivery-116d0.appspot.com',
    measurementId: 'G-D4XBKTBZEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcathU9-vVXAjtGS3wPH-jhzDaXwysBPQ',
    appId: '1:941029947680:android:a83954af56bbfe110eff45',
    messagingSenderId: '941029947680',
    projectId: 'food-delivery-116d0',
    storageBucket: 'food-delivery-116d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0h0bnmcmxlMjHrgxKgCHpIxbV2wGwFso',
    appId: '1:941029947680:ios:e8e03b77827124220eff45',
    messagingSenderId: '941029947680',
    projectId: 'food-delivery-116d0',
    storageBucket: 'food-delivery-116d0.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0h0bnmcmxlMjHrgxKgCHpIxbV2wGwFso',
    appId: '1:941029947680:ios:5fadc8892053c6e00eff45',
    messagingSenderId: '941029947680',
    projectId: 'food-delivery-116d0',
    storageBucket: 'food-delivery-116d0.appspot.com',
    iosBundleId: 'com.example.foodDelivery.RunnerTests',
  );
}
